default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL', '') %>

development:
  <<: *default
  database: url_shortener_development

test:
  <<: *default
  database: url_shortener_test

production:
  <<: *default
  database: url_shortener_production
